# Generated by Django 4.2.6 on 2024-10-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(help_text='Duration of the song (e.g. 00:03:30)', null=True),
        ),
    ]
