# Generated by Django 4.2.6 on 2024-10-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_song_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mp3_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
