# Generated by Django 4.2.6 on 2024-10-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_song_mp3_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mp3_path',
        ),
        migrations.AddField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='mp3_files/'),
        ),
    ]
